const express = require('express');
const router = express.Router();
const crypto = require('crypto');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { verifyPortalToken } = require('../middleware/portalAuth.cjs');
const repoCanonical = require('../services/supabaseCanonicalRepository.cjs');
const portalService = require('../services/portalService.cjs');
const portalAuthService = require('../services/portalAuthService.cjs');
const portalLifecycleService = require('../services/portalLifecycleService.cjs');
const paymentRequestService = require('../services/paymentRequestService.cjs');
const officialDocumentService = require('../services/officialDocumentService.cjs');
const { sensitiveLimiter, apiLimiter } = require('../middleware/rateLimiter.cjs');
const { idempotencyMiddleware } = require('../middleware/idempotency.cjs');

// Ensure ticket attachments upload directory exists
const TICKET_ATTACHMENTS_DIR = path.join(__dirname, '..', 'storage', 'ticket-attachments');
fs.mkdirSync(TICKET_ATTACHMENTS_DIR, { recursive: true });

// Multer storage configuration for ticket attachments
const ticketAttachmentStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, TICKET_ATTACHMENTS_DIR);
  },
  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname);
    const uniqueName = `${crypto.randomUUID()}${ext}`;
    cb(null, uniqueName);
  },
});

const uploadTicketAttachment = multer({
  storage: ticketAttachmentStorage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB max
  fileFilter: (req, file, cb) => {
    const allowedTypes = [
      'image/jpeg', 'image/png', 'image/gif', 'image/webp',
      'application/pdf', 'text/plain', 'text/csv',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/zip', 'application/x-zip-compressed',
    ];
    if (allowedTypes.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error('File type not allowed'), false);
    }
  },
});

let stripe = null;
try {
  const Stripe = require('stripe');
  if (process.env.STRIPE_SECRET_KEY) {
    stripe = new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2024-06-20' });
  }
} catch { /* stripe not installed or no key — payment will use mock mode */ }

const GLOBAL_PORTAL_LIMIT = apiLimiter({ windowMs: 15 * 60 * 1000, maxRequests: 200 });
const SENSITIVE_PORTAL_LIMIT = sensitiveLimiter({ windowMs: 60 * 60 * 1000, maxRequests: 30 });

router.use(verifyPortalToken);
router.use(GLOBAL_PORTAL_LIMIT);

function requestContext(req) {
  return {
    ip: req.ip || req.headers['x-forwarded-for'] || null,
    userAgent: req.headers['user-agent'] || null,
    method: req.method,
    path: req.originalUrl,
    correlationId: req.correlationId,
  };
}

// ─── Official document downloads (ERP-authoritative PDF) ────────────────────
//
// Streams the OFFICIAL document generated by the ERP's own renderer
// (PrimeDocument pipeline) for records the authenticated customer owns.
//   - Customer identity: portal JWT only; the record is fetched through the
//     existing customer-scoped getters, so foreign ids resolve to NOT_FOUND
//     (existence is never leaked across customers).
//   - Transport: Option A — application/pdf bytes with Content-Disposition.
//   - Audit: reuses the gated download audit trail (best-effort).
async function sendOfficialDocument(req, res, { docType, fetchRecord, resolveFilename, renderType }) {
  try {
    const { id, customer_id } = req.portalUser;
    const record = await fetchRecord(id, customer_id);
    if (!record) {
      return res.status(404).json({ error: 'Document not found' });
    }

    // Gated + audited download marker (same audit trail as /downloads).
    try {
      await portalLifecycleService.recordDownload({
        docType,
        docId: record.id || id,
        portalUserId: id,
        customerId: customer_id,
        context: requestContext(req),
      });
    } catch (_) { /* audit is best-effort; never blocks an authorized download */ }

    const ownerCustomer = await repoCanonical.getById('customers', customer_id).catch(() => null);
    const { buffer } = await officialDocumentService.renderOfficialPdf({
      type: renderType,
      rawData: record,
      customers: ownerCustomer ? [ownerCustomer] : [],
      channel: 'portal',
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', officialDocumentService.buildContentDisposition(resolveFilename(record)));
    res.setHeader('Cache-Control', 'no-store');
    return res.status(200).send(buffer);
  } catch (err) {
    if (err.code === 'RENDERER_UNAVAILABLE') {
      console.error('[Portal] Official document renderer not configured:', err.message);
      return res.status(503).json({ error: 'official_document_renderer_unconfigured' });
    }
    console.error(`[Portal] Official ${docType} document failed:`, err.message);
    return res.status(500).json({ error: 'official_document_generation_failed' });
  }
}

router.get('/invoices/:id/document', async (req, res) => {
  await sendOfficialDocument(req, res, {
    docType: 'invoice',
    renderType: 'INVOICE',
    fetchRecord: async (_userId, customerId) => {
      const invoice = await portalService.getInvoiceById(req.params.id, customerId);
      if (!invoice) return null;
      const ownerCustomer = await repoCanonical.getById('customers', customerId).catch(() => null);
      if (ownerCustomer) {
        invoice.totalCustomerOutstanding = Number(ownerCustomer.outstandingBalance ?? ownerCustomer.balance ?? 0);
        invoice.walletBalance = Number(ownerCustomer.walletBalance ?? ownerCustomer.wallet_balance ?? 0);
      }
      return invoice;
    },
    resolveFilename: (r) => `${r.invoiceNumber || r.invoice_number || r.id}.pdf`,
  });
});

router.get('/quotations/:id/document', async (req, res) => {
  await sendOfficialDocument(req, res, {
    docType: 'quotation',
    renderType: 'QUOTATION',
    fetchRecord: async (_userId, customerId) =>
      portalLifecycleService.getQuotationById(req.params.id, { customerId }),
    resolveFilename: (r) => `${r.quotationNumber || r.quotation_number || r.number || r.id}.pdf`,
  });
});

router.get('/orders/:id/document', async (req, res) => {
  await sendOfficialDocument(req, res, {
    docType: 'order',
    renderType: 'SALES_ORDER',
    fetchRecord: async (_userId, customerId) =>
      portalService.getOrderById(req.params.id, customerId),
    resolveFilename: (r) => `${r.orderNumber || r.order_number || r.id}.pdf`,
  });
});

// ─── Payment Receipt (ERP-authoritative PDF) ────────────────────────────────
//
// Generates an OFFICIAL payment receipt PDF from the ERP's authoritative
// payment record. The receipt is a READ-ONLY representation of an existing
// payment — it MUST NOT create, allocate, or modify any accounting data.
//
// The receipt data is mapped from the actual customer_payments record,
// including its invoice allocations, using the same PrimeDocument RECEIPT
// renderer the ERP staff UI uses.
router.get('/payments/:id/document', async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    const payment = await portalService.getPaymentById(req.params.id, customer_id);
    if (!payment) {
      return res.status(404).json({ error: 'Payment not found' });
    }

    // Gated + audited download marker (best-effort).
    try {
      await portalLifecycleService.recordDownload({
        docType: 'payment_receipt',
        docId: payment.id || req.params.id,
        portalUserId: id,
        customerId: customer_id,
        context: requestContext(req),
      });
    } catch (_) { /* audit is best-effort; never blocks an authorized download */ }

    const ownerCustomer = await repoCanonical.getById('customers', customer_id).catch(() => null);
    const receiptData = portalService.mapPaymentToReceiptData(payment, ownerCustomer);

    const { buffer } = await officialDocumentService.renderOfficialPdf({
      type: 'RECEIPT',
      rawData: receiptData,
      customers: ownerCustomer ? [ownerCustomer] : [],
      channel: 'portal',
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', officialDocumentService.buildContentDisposition(
      `Receipt-${receiptData.receiptNumber}.pdf`
    ));
    res.setHeader('Cache-Control', 'no-store');
    return res.status(200).send(buffer);
  } catch (err) {
    if (err.code === 'RENDERER_UNAVAILABLE') {
      console.error('[Portal] Official document renderer not configured:', err.message);
      return res.status(503).json({ error: 'official_document_renderer_unconfigured' });
    }
    console.error('[Portal] Official payment receipt document failed:', err.message);
    return res.status(500).json({ error: 'official_document_generation_failed' });
  }
});

// ─── Delivery Note (ERP-authoritative PDF) ──────────────────────────────────
//
// Generates an OFFICIAL delivery note PDF from the ERP's authoritative
// delivery note record (delivery_notes table). The note is a READ-ONLY
// representation of an existing fulfillment record — it MUST NOT create a
// delivery, alter delivered quantity, modify inventory, or change order status.
//
// The delivery note data passes through the existing PrimeDocument DELIVERY_NOTE
// renderer (same as the ERP staff UI's Shipping Manager preview).
router.get('/deliveries/:id/document', async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    const note = await portalService.getDeliveryNoteForDelivery(req.params.id, customer_id);
    if (!note) {
      return res.status(404).json({ error: 'Delivery note not found' });
    }

    // Gated + audited download marker (best-effort).
    try {
      await portalLifecycleService.recordDownload({
        docType: 'delivery_note',
        docId: note.id || req.params.id,
        portalUserId: id,
        customerId: customer_id,
        context: requestContext(req),
      });
    } catch (_) { /* audit is best-effort; never blocks an authorized download */ }

    const ownerCustomer = await repoCanonical.getById('customers', customer_id).catch(() => null);
    const { buffer } = await officialDocumentService.renderOfficialPdf({
      type: 'DELIVERY_NOTE',
      rawData: note,
      customers: ownerCustomer ? [ownerCustomer] : [],
      channel: 'portal',
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', officialDocumentService.buildContentDisposition(
      `Delivery-Note-${note.dnNumber || note.deliveryNoteNumber || note.id}.pdf`
    ));
    res.setHeader('Cache-Control', 'no-store');
    return res.status(200).send(buffer);
  } catch (err) {
    if (err.code === 'RENDERER_UNAVAILABLE') {
      console.error('[Portal] Official document renderer not configured:', err.message);
      return res.status(503).json({ error: 'official_document_renderer_unconfigured' });
    }
    console.error('[Portal] Official delivery note document failed:', err.message);
    return res.status(500).json({ error: 'official_document_generation_failed' });
  }
});

// ─── Customer Statement (ERP-authoritative PDF) ─────────────────────────────
//
// Generates an OFFICIAL customer account statement PDF from the ERP's
// authoritative ledger (customerLedger.cjs). The statement is a READ-ONLY
// representation — it MUST NOT create transactions, modify balances, or
// write ledger records.
//
// Period contract: ?from=YYYY-MM-DD&to=YYYY-MM-DD (optional).
// Defaults to the last 365 days when no period is specified.
router.get('/customers/statement/document', async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    let { from, to } = req.query || {};

    // Default period: last 365 days.
    if (!from || !to) {
      const now = new Date();
      const end = now.toISOString().split('T')[0];
      const start = new Date(now.getTime() - 365 * 86400000).toISOString().split('T')[0];
      from = from || start;
      to = to || end;
    }

    // Statement data is fetched from the authoritative portal service
    // (which uses customerLedger.buildLedger internally).
    const statementsData = await portalService.getStatements(customer_id, from, to);
    if (!statementsData) {
      return res.status(404).json({ error: 'Statement data not found' });
    }

    // Attach period metadata for the renderer.
    statementsData.startDate = from;
    statementsData.endDate = to;

    // Gated + audited download marker (best-effort).
    try {
      await portalLifecycleService.recordDownload({
        docType: 'statement',
        docId: `statement_${customer_id}_${from}_${to}`,
        portalUserId: id,
        customerId: customer_id,
        context: requestContext(req),
      });
    } catch (_) { /* audit is best-effort; never blocks an authorized download */ }

    const ownerCustomer = await repoCanonical.getById('customers', customer_id).catch(() => null);
    const statementData = portalService.buildStatementData(customer_id, ownerCustomer, statementsData);

    const { buffer } = await officialDocumentService.renderOfficialPdf({
      type: 'ACCOUNT_STATEMENT',
      rawData: statementData,
      customers: ownerCustomer ? [ownerCustomer] : [],
      channel: 'portal',
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', officialDocumentService.buildContentDisposition(
      `Statement-${statementData.customerName}_${from}_to_${to}.pdf`
    ));
    res.setHeader('Cache-Control', 'no-store');
    return res.status(200).send(buffer);
  } catch (err) {
    if (err.code === 'RENDERER_UNAVAILABLE') {
      console.error('[Portal] Official document renderer not configured:', err.message);
      return res.status(503).json({ error: 'official_document_renderer_unconfigured' });
    }
    console.error('[Portal] Official statement document failed:', err.message);
    return res.status(500).json({ error: 'official_document_generation_failed' });
  }
});

// ─── Realtime events (SSE) — no manual refresh needed ────────────────────────
router.post('/events-ticket', SENSITIVE_PORTAL_LIMIT, async (req, res) => {
  try {
    const { id, customer_id, email } = req.portalUser;
    const ticket = portalAuthService.generateEventTicket({ id, customer_id, email }, 'portal');
    res.json({ ticket, expiresIn: 300 });
  } catch (err) {
    console.error('[Portal] events-ticket error:', err);
    res.status(500).json({ error: 'Failed to issue realtime ticket' });
  }
});
router.get('/events', (req, res) => {
  const unsubscribe = portalLifecycleService.subscribePortal(req, res);
  res.on('close', unsubscribe);
});

router.get('/catalog', async (req, res) => {
  try {
    const data = await portalService.getCatalog();
    res.json(data);
  } catch (err) {
    console.error('[Portal] Catalog error:', err);
    res.status(500).json({ error: 'Failed to load catalog' });
  }
});

// ─── Promotions (display-only: active PORTAL promotions for badges/banners) ──
router.get('/promotions', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalLifecycleService.getActivePortalPromotions(customer_id);
    res.json(data);
  } catch (err) {
    console.error('[Portal] Promotions error:', err);
    res.status(500).json({ error: 'Failed to load promotions' });
  }
});

// ─── Banner Ads (display-only: active portal banner ads) ────────────────────
router.get('/ads', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalLifecycleService.getActivePortalAds(customer_id);
    res.json(data);
  } catch (err) {
    console.error('[Portal] Ads error:', err);
    res.status(500).json({ error: 'Failed to load ads' });
  }
});

// ─── Order preview — server-authoritative promotion calculation ──────────────
// The portal may show this estimate; the backend re-calculates at submission.
router.post('/orders/preview', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { items, promotionCode } = req.body || {};
    if (!items || !Array.isArray(items) || items.length === 0) {
      return res.status(400).json({ error: 'At least one line item is required' });
    }
    const data = await portalLifecycleService.previewOrder({
      customerId: customer_id,
      items,
      promotionCode: promotionCode || null,
    });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Order preview error:', err);
    res.status(400).json({ error: err.message || 'Failed to preview order' });
  }
});

// ─── Quotation Requests (customer-submitted, NOT official documents) ────────
router.get('/requests', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { page, pageSize, status, search } = req.query;
    const hasPagination = page || pageSize;
    if (hasPagination) {
      const data = await portalService.getRequestsPaginated(customer_id, {
        page: page ? parseInt(page, 10) : 1,
        pageSize: Math.min(100, Math.max(1, parseInt(pageSize, 10) || 20)),
        status: status || undefined,
        search: search || undefined,
      });
      return res.json(data);
    }
    const data = await portalLifecycleService.getRequests({ customerId: customer_id });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Requests error:', err);
    res.status(500).json({ error: 'Failed to load requests' });
  }
});

router.post('/requests', idempotencyMiddleware(), async (req, res) => {
  try {
    const { id, customer_id, email, full_name, referred_by_code } = req.portalUser;
    const { requestType, items, notes, requestedDeliveryDate, attachments, reorderOf, reorderOfNumber, promotionCode } = req.body;
    if (!items || !Array.isArray(items) || items.length === 0) {
      return res.status(400).json({ error: 'At least one line item is required' });
    }
    const customerRecord = customer_id ? await repoCanonical.getById('customers', customer_id).catch(() => null) : null;
    const customerName = (customerRecord && customerRecord.name) || full_name || email || 'Customer';
    const result = await portalLifecycleService.createQuotationRequest({
      portalUserId: id,
      customerId: customer_id,
      customerName,
      requestType,
      items,
      notes,
      requestedDeliveryDate,
      attachments,
      reorderOf: reorderOf || null,
      reorderOfNumber: reorderOfNumber || null,
      promotionCode: promotionCode || null,
      referredByCode: referred_by_code || null,
      context: requestContext(req),
    });
    res.status(201).json(result);
  } catch (err) {
    console.error('[Portal] Create request error:', err);
    res.status(400).json({ error: err.message || 'Failed to submit request' });
  }
});

router.get('/requests/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalLifecycleService.getRequestById(req.params.id, { customerId: customer_id });
    if (!data) return res.status(404).json({ error: 'Request not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Request detail error:', err);
    res.status(500).json({ error: 'Failed to load request' });
  }
});

router.post('/requests/:id/cancel', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const result = await portalLifecycleService.cancelRequest(req.params.id, {
      portalUserId: id,
      customerId: customer_id,
      context: requestContext(req),
    });
    res.json(result);
  } catch (err) {
    console.error('[Portal] Cancel request error:', err);
    res.status(400).json({ error: err.message || 'Failed to cancel request' });
  }
});

// ─── Quotations (official documents — read-only for customers) ──────────────
router.get('/quotations/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalLifecycleService.getQuotationById(req.params.id, { customerId: customer_id });
    if (!data) return res.status(404).json({ error: 'Quotation not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Quotation detail error:', err);
    res.status(500).json({ error: 'Failed to load quotation' });
  }
});

router.post('/quotations/:id/accept', async (req, res) => {
  try {
    const { id, customer_id, email, full_name } = req.portalUser;
    const result = await portalLifecycleService.acceptQuotation(req.params.id, {
      portalUserId: id,
      customerId: customer_id,
      signerName: full_name || email || null,
      signerEmail: email || null,
      context: requestContext(req),
    });
    res.json(result);
  } catch (err) {
    console.error('[Portal] Accept quotation error:', err);
    res.status(400).json({ error: err.message || 'Failed to accept quotation' });
  }
});

router.post('/quotations/:id/reject', async (req, res) => {
  try {
    const { id, customer_id, email, full_name } = req.portalUser;
    const { reason } = req.body || {};
    const result = await portalLifecycleService.rejectQuotation(req.params.id, {
      portalUserId: id,
      customerId: customer_id,
      reason,
      signerName: full_name || email || null,
      signerEmail: email || null,
      context: requestContext(req),
    });
    res.json(result);
  } catch (err) {
    console.error('[Portal] Reject quotation error:', err);
    res.status(400).json({ error: err.message || 'Failed to reject quotation' });
  }
});

router.post('/quotations/:id/revision', async (req, res) => {
  try {
    const { id, customer_id, email, full_name } = req.portalUser;
    const { comments } = req.body || {};
    const result = await portalLifecycleService.requestRevision(req.params.id, {
      portalUserId: id,
      customerId: customer_id,
      comments,
      signerName: full_name || email || null,
      signerEmail: email || null,
      context: requestContext(req),
    });
    res.json(result);
  } catch (err) {
    console.error('[Portal] Revision request error:', err);
    res.status(400).json({ error: err.message || 'Failed to request revision' });
  }
});

// ─── Quotation version history (Phase 3) ─────────────────────────────────────
router.get('/quotations/:id/versions', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const quotation = await portalLifecycleService.getQuotationById(req.params.id, { customerId: customer_id });
    if (!quotation) return res.status(404).json({ error: 'Quotation not found' });
    const data = await portalLifecycleService.listDocumentVersions('quotation', req.params.id, { });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Quotation versions error:', err);
    res.status(500).json({ error: 'Failed to load quotation versions' });
  }
});

router.get('/quotations/:id/versions/:version', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const quotation = await portalLifecycleService.getQuotationById(req.params.id, { customerId: customer_id });
    if (!quotation) return res.status(404).json({ error: 'Quotation not found' });
    const data = await portalLifecycleService.getDocumentVersion('quotation', req.params.id, Number(req.params.version), { });
    if (!data) return res.status(404).json({ error: 'Version not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Quotation version detail error:', err);
    res.status(500).json({ error: 'Failed to load quotation version' });
  }
});

// ─── Quotation decision signatures (Phase 3) ─────────────────────────────────
router.get('/quotations/:id/signatures', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const quotation = await portalLifecycleService.getQuotationById(req.params.id, { customerId: customer_id });
    if (!quotation) return res.status(404).json({ error: 'Quotation not found' });
    const data = await portalLifecycleService.getDocumentSignatures('quotation', req.params.id, { customerId: customer_id });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Quotation signatures error:', err);
    res.status(500).json({ error: 'Failed to load signatures' });
  }
});

// ─── Document discussions (Phase 4) ──────────────────────────────────────────
router.get('/comments', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { docType, docId } = req.query;
    if (!docType || !docId) {
      return res.status(400).json({ error: 'docType and docId are required' });
    }
    const data = await portalLifecycleService.getComments({
      docType, docId, customerId: customer_id, view: 'customer',
    });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Comments error:', err);
    res.status(500).json({ error: 'Failed to load comments' });
  }
});

router.post('/comments', async (req, res) => {
  try {
    const { id, customer_id, email, full_name } = req.portalUser;
    const { docType, docId, body } = req.body || {};
    if (!docType || !docId || !body) {
      return res.status(400).json({ error: 'docType, docId and body are required' });
    }
    const data = await portalLifecycleService.addComment({
      docType, docId, customerId: customer_id,
      actor: { type: 'customer', id, name: full_name || email || 'Customer' },
      body,
      context: requestContext(req),
    });
    res.status(201).json(data);
  } catch (err) {
    console.error('[Portal] Add comment error:', err);
    res.status(400).json({ error: err.message || 'Failed to add comment' });
  }
});

// ─── Downloads (gated + audited) ─────────────────────────────────────────────
router.post('/downloads', SENSITIVE_PORTAL_LIMIT, async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const { docType, docId } = req.body || {};
    if (!docType || !docId) {
      return res.status(400).json({ error: 'docType and docId are required' });
    }
    const result = await portalLifecycleService.recordDownload({
      docType,
      docId,
      portalUserId: id,
      customerId: customer_id,
      context: requestContext(req),
    });
    res.json(result);
  } catch (err) {
    console.error('[Portal] Download audit error:', err);
    res.status(400).json({ error: err.message || 'Download not permitted' });
  }
});

// ─── Timeline (merged chronological history per document) ────────────────────
router.get('/timeline', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { docType, docId } = req.query;
    if (!docType || !docId) {
      return res.status(400).json({ error: 'docType and docId are required' });
    }
    const data = await portalLifecycleService.getTimeline({
      docType,
      docId,
      customerId: customer_id,
    });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Timeline error:', err);
    res.status(500).json({ error: 'Failed to load timeline' });
  }
});

// ─── Dashboard ────────────────────────────────────────────────
router.get('/dashboard', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const data = await portalService.getDashboard(id, customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Dashboard error:', err);
    res.status(500).json({ error: 'Failed to load dashboard' });
  }
});

// ─── Orders ───────────────────────────────────────────────────
router.get('/orders', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { page, pageSize, status, search, dateFrom, dateTo } = req.query;
    const hasPagination = page || pageSize;
    if (hasPagination) {
      const data = await portalService.getOrdersPaginated(customer_id, {
        page: page ? parseInt(page, 10) : 1,
        pageSize: Math.min(100, Math.max(1, parseInt(pageSize, 10) || 20)),
        status: status || undefined,
        search: search || undefined,
        dateFrom: dateFrom || undefined,
        dateTo: dateTo || undefined,
      });
      return res.json(data);
    }
    const data = await portalService.getOrders(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Orders error:', err);
    res.status(500).json({ error: 'Failed to load orders' });
  }
});

router.get('/orders/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getOrderById(req.params.id, customer_id );
    if (!data) return res.status(404).json({ error: 'Order not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Order detail error:', err);
    res.status(500).json({ error: 'Failed to load order' });
  }
});

// Reorder an official sales order — creates a brand-new order request
// (ODR-YYYY-######) so the order goes through sales review again.
router.post('/orders/:id/reorder', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const result = await portalLifecycleService.reorderFromOrder(req.params.id, {
      portalUserId: id,
      customerId: customer_id,
      context: requestContext(req),
    });
    res.status(201).json(result);
  } catch (err) {
    console.error('[Portal] Reorder error:', err);
    res.status(400).json({ error: err.message || 'Failed to reorder' });
  }
});

// ─── Document chain (request → quotation → sales order) ────────────────────
router.get('/document-chain', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { docType, docId } = req.query;
    if (!docType || !docId) {
      return res.status(400).json({ error: 'docType and docId are required' });
    }
    const data = await portalLifecycleService.getDocumentChain({
      docType,
      docId,
      customerId: customer_id,
    });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Document chain error:', err);
    res.status(400).json({ error: err.message || 'Failed to load document chain' });
  }
});

// ─── Quotations ───────────────────────────────────────────────
router.get('/quotations', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { page, pageSize, status, search } = req.query;
    const hasPagination = page || pageSize;
    if (hasPagination) {
      const data = await portalService.getQuotationsPaginated(customer_id, {
        page: page ? parseInt(page, 10) : 1,
        pageSize: Math.min(100, Math.max(1, parseInt(pageSize, 10) || 20)),
        status: status || undefined,
        search: search || undefined,
      });
      return res.json(data);
    }
    const data = await portalService.getQuotations(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Quotations error:', err);
    res.status(500).json({ error: 'Failed to load quotations' });
  }
});

// ─── Invoices ─────────────────────────────────────────────────
router.get('/invoices', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { page, pageSize, status, search, dateFrom, dateTo } = req.query;
    const hasPagination = page || pageSize;
    if (hasPagination) {
      const data = await portalService.getInvoicesPaginated(customer_id, {
        page: page ? parseInt(page, 10) : 1,
        pageSize: Math.min(100, Math.max(1, parseInt(pageSize, 10) || 20)),
        status: status || undefined,
        search: search || undefined,
        dateFrom: dateFrom || undefined,
        dateTo: dateTo || undefined,
      });
      return res.json(data);
    }
    const data = await portalService.getInvoices(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Invoices error:', err);
    res.status(500).json({ error: 'Failed to load invoices' });
  }
});

router.get('/invoices/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getInvoiceById(req.params.id, customer_id );
    if (!data) return res.status(404).json({ error: 'Invoice not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Invoice detail error:', err);
    res.status(500).json({ error: 'Failed to load invoice' });
  }
});

// Revert the latest payment on an invoice back to unpaid (testing / corrections).
// DISABLED: This endpoint bypasses ERP accounting rules and was intended for testing only.
// A normal portal customer must not be able to arbitrarily revert an ERP invoice.
// To revert a payment, use the ERP admin interface.
router.post('/invoices/:id/revert', async (req, res) => {
  res.status(403).json({ error: 'This feature is not available in the portal. Please contact your administrator to revert a payment.' });
});

// ─── Payment Requests (NON-ACCOUNTING bank-transfer intentions) ────────────
// A payment request is customer intent to pay by bank transfer — workflow data
// only. It NEVER creates a customer_payments row, payment allocation, Stripe
// intent, or modifies the invoice. The actual bank payment happens outside the
// portal; ERP staff later record the real accounting payment through the
// existing ERP payment workflow.
//
// SECURITY: customer identity (customer_id) is derived from the portal JWT —
// NEVER from the request body. The body carries only customer-controlled
// fields: invoiceId, requestedAmount?, note?.
router.post('/payment-requests', async (req, res) => {
  try {
    const { id: portalUserId, customer_id, email, full_name } = req.portalUser;
    const { invoiceId, requestedAmount, note } = req.body || {};
    if (!invoiceId) {
      return res.status(400).json({ error: 'invoiceId is required' });
    }
    const result = await paymentRequestService.createRequest({
      customerId: customer_id,
      customerName: full_name || email || 'Customer',
      invoiceId,
      requestedAmount,
      note,
      portalUserId,
      context: requestContext(req),
    });
    res.status(201).json(paymentRequestService.toPortalDto(result));
  } catch (err) {
    console.error('[Portal] Create payment request error:', err.message);
    const status = /not found/i.test(err.message) ? 404 : 400;
    res.status(status).json({ error: err.message || 'Failed to create payment request' });
  }
});

router.get('/payment-requests', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const rows = await paymentRequestService.getRequestsForCustomer(customer_id);
    res.json((rows || []).map(paymentRequestService.toPortalDto));
  } catch (err) {
    console.error('[Portal] Payment requests error:', err.message);
    res.status(500).json({ error: 'Failed to load payment requests' });
  }
});

router.get('/payment-requests/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const row = await paymentRequestService.getRequestById(req.params.id, customer_id);
    if (!row) return res.status(404).json({ error: 'Payment request not found' });
    res.json(paymentRequestService.toPortalDto(row));
  } catch (err) {
    console.error('[Portal] Payment request detail error:', err.message);
    res.status(500).json({ error: 'Failed to load payment request' });
  }
});

// ─── Payments ─────────────────────────────────────────────────
router.get('/payments', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { page, pageSize, search, dateFrom, dateTo } = req.query;
    const hasPagination = page || pageSize;
    if (hasPagination) {
      const data = await portalService.getPaymentsPaginated(customer_id, {
        page: page ? parseInt(page, 10) : 1,
        pageSize: Math.min(100, Math.max(1, parseInt(pageSize, 10) || 20)),
        search: search || undefined,
        dateFrom: dateFrom || undefined,
        dateTo: dateTo || undefined,
      });
      return res.json(data);
    }
    const data = await portalService.getPayments(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Payments error:', err);
    res.status(500).json({ error: 'Failed to load payments' });
  }
});

router.get('/payments/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getPaymentById(req.params.id, customer_id );
    if (!data) return res.status(404).json({ error: 'Payment not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Payment detail error:', err);
    res.status(500).json({ error: 'Failed to load payment' });
  }
});

// ─── Statements ───────────────────────────────────────────────
router.get('/statements', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { startDate, endDate } = req.query;
    const data = await portalService.getStatements(customer_id, startDate, endDate);
    res.json(data);
  } catch (err) {
    console.error('[Portal] Statements error:', err);
    res.status(500).json({ error: 'Failed to load statements' });
  }
});

// ─── Loyalty ──────────────────────────────────────────────────
router.get('/loyalty', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getLoyalty(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Loyalty error:', err);
    res.status(500).json({ error: 'Failed to load loyalty data' });
  }
});

// ─── Wallet ───────────────────────────────────────────────────
router.get('/wallet', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getWallet(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Wallet error:', err);
    res.status(500).json({ error: 'Failed to load wallet data' });
  }
});

// ─── Profile ──────────────────────────────────────────────────
router.get('/profile', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getProfile(customer_id );
    if (!data) return res.status(404).json({ error: 'Profile not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Profile error:', err);
    res.status(500).json({ error: 'Failed to load profile' });
  }
});

router.put('/profile', async (req, res) => {
  try {
    const { id } = req.portalUser;
    const { full_name, phone, email, address, city, state, zip, country } = req.body;
    await portalAuthService.updatePortalUser(id, { full_name, phone, email, address, city, state, zip, country });
    res.json({ message: 'Profile updated successfully' });
  } catch (err) {
    console.error('[Portal] Profile update error:', err);
    res.status(500).json({ error: 'Failed to update profile' });
  }
});

router.put('/profile/password', SENSITIVE_PORTAL_LIMIT, async (req, res) => {
  try {
    const { id } = req.portalUser;
    const { currentPassword, newPassword } = req.body;
    if (!currentPassword || !newPassword) {
      return res.status(400).json({ error: 'Current password and new password are required' });
    }
    if (newPassword.length < 6) {
      return res.status(400).json({ error: 'New password must be at least 6 characters' });
    }
    await portalAuthService.changePassword(id, currentPassword, newPassword);
    res.json({ message: 'Password changed successfully' });
  } catch (err) {
    console.error('[Portal] Password change error:', err);
    if (err.message === 'Current password is incorrect') {
      return res.status(400).json({ error: err.message });
    }
    res.status(500).json({ error: 'Failed to change password' });
  }
});

// ─── Documents ────────────────────────────────────────────────
router.get('/documents', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getDocuments(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Documents error:', err);
    res.status(500).json({ error: 'Failed to load documents' });
  }
});

// ─── Notifications ────────────────────────────────────────────
router.get('/notifications', async (req, res) => {
  try {
    const { id } = req.portalUser;
    const data = await portalService.getNotifications(id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Notifications error:', err);
    res.status(500).json({ error: 'Failed to load notifications' });
  }
});

router.put('/notifications/:id/read', async (req, res) => {
  try {
    const { id } = req.portalUser;
    await portalService.markNotificationRead(req.params.id, id);
    res.json({ success: true });
  } catch (err) {
    console.error('[Portal] Mark notification read error:', err);
    res.status(500).json({ error: 'Failed to mark notification as read' });
  }
});

router.get('/notifications/unread-count', async (req, res) => {
  try {
    const { id } = req.portalUser;
    const count = await portalService.getUnreadNotificationCount(id );
    res.json({ count });
  } catch (err) {
    console.error('[Portal] Unread count error:', err);
    res.status(500).json({ error: 'Failed to load unread count' });
  }
});

router.put('/notifications/read-all', async (req, res) => {
  try {
    const { id } = req.portalUser;
    await portalService.markAllNotificationsRead(id );
    res.json({ success: true });
  } catch (err) {
    console.error('[Portal] Mark all read error:', err);
    res.status(500).json({ error: 'Failed to mark all notifications as read' });
  }
});

// ─── Referrals ────────────────────────────────────────────────
router.get('/referrals/code', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getReferralCode(req.portalUser.id, customer_id);
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referral code error:', err);
    res.status(500).json({ error: 'Failed to load referral code' });
  }
});

router.get('/referrals', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const { page, pageSize, status, search, sort } = req.query;
    const data = await portalService.getReferrals(id, customer_id, {
      page: page ? parseInt(page, 10) : 1,
      pageSize: pageSize ? parseInt(pageSize, 10) : 20,
      status: status || undefined,
      search: search || undefined,
      sort: sort || 'date_desc',
    });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referrals error:', err);
    res.status(500).json({ error: err.message || 'Failed to load referrals' });
  }
});

router.get('/referrals/rewards', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const { page, pageSize, status } = req.query;
    const data = await portalService.getReferralRewards(id, customer_id, {
      page: page ? parseInt(page, 10) : 1,
      pageSize: pageSize ? parseInt(pageSize, 10) : 20,
      status: status || undefined,
    });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referral rewards error:', err);
    res.status(500).json({ error: 'Failed to load rewards' });
  }
});

router.get('/referrals/settings', async (req, res) => {
  try {
    const data = await portalService.getReferralSettings();
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referral settings error:', err);
    res.status(500).json({ error: 'Failed to load referral settings' });
  }
});

router.get('/referrals/stats', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getReferralFunnelStats(customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referral stats error:', err);
    res.status(500).json({ error: 'Failed to load referral stats' });
  }
});

router.get('/referrals/:id/timeline', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const data = await portalService.getReferralTimeline(req.params.id, customer_id);
    if (data === null) return res.status(404).json({ error: 'Referral not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referral timeline error:', err);
    res.status(500).json({ error: 'Failed to load timeline' });
  }
});

router.get('/referrals/:id', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const data = await portalService.getReferralById(req.params.id, id, customer_id );
    if (!data) return res.status(404).json({ error: 'Referral not found' });
    res.json(data);
  } catch (err) {
    console.error('[Portal] Referral detail error:', err);
    res.status(500).json({ error: 'Failed to load referral' });
  }
});

router.post('/referrals', idempotencyMiddleware(), async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const { referredCustomerId, notes } = req.body || {};
    if (!referredCustomerId) {
      return res.status(400).json({ error: 'Referred customer is required' });
    }
    const data = await portalService.createReferral(id, customer_id, {
      referredCustomerId,
      notes,
    });
    res.status(201).json(data);
  } catch (err) {
    console.error('[Portal] Create referral error:', err);
    res.status(400).json({ error: err.message || 'Failed to create referral' });
  }
});

router.get('/referrals/customers/search', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { q } = req.query;
    if (!q || String(q).trim().length < 2) {
      return res.json([]);
    }
    const data = await portalService.searchCustomersForReferral( String(q), customer_id);
    res.json(data);
  } catch (err) {
    console.error('[Portal] Customer search error:', err);
    res.status(500).json({ error: 'Failed to search customers' });
  }
});

// ─── Support Tickets ──────────────────────────────────────────
router.get('/support/tickets', async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const data = await portalService.getSupportTickets(id, customer_id );
    res.json(data);
  } catch (err) {
    console.error('[Portal] Support tickets error:', err);
    res.status(500).json({ error: 'Failed to load tickets' });
  }
});

router.post('/support/tickets', SENSITIVE_PORTAL_LIMIT, async (req, res) => {
  try {
    const { id, customer_id} = req.portalUser;
    const { subject, message, priority } = req.body;
    if (!subject || !message) {
      return res.status(400).json({ error: 'Subject and message are required' });
    }
    const ticket = await portalService.createSupportTicket(id, customer_id, { subject, message, priority });
    res.status(201).json(ticket);
  } catch (err) {
    console.error('[Portal] Create ticket error:', err);
    res.status(500).json({ error: 'Failed to create ticket' });
  }
});

router.post('/support/tickets/:id/messages', async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    const { message } = req.body;
    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }
    const msg = await portalService.addTicketMessage(req.params.id, id, customer_id, message);
    res.status(201).json(msg);
  } catch (err) {
    console.error('[Portal] Add message error:', err);
    res.status(500).json({ error: 'Failed to add message' });
  }
});

router.put('/support/tickets/:id/status', async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    const { status } = req.body;
    if (!status) {
      return res.status(400).json({ error: 'Status is required' });
    }
    const result = await portalService.updateTicketStatus(req.params.id, id, customer_id, status);
    res.json(result);
  } catch (err) {
    console.error('[Portal] Update ticket status error:', err);
    res.status(500).json({ error: 'Failed to update ticket status' });
  }
});

// ─── Support Ticket Attachments ──────────────────────────────────
router.post('/support/tickets/:id/attachments', uploadTicketAttachment.single('file'), async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    const { message_id } = req.body;
    if (!req.file) {
      return res.status(400).json({ error: 'File is required' });
    }
    const attachment = await portalService.uploadTicketAttachment(
      req.params.id,
      id,
      customer_id,
      req.file,
      message_id || null
    );
    res.status(201).json(attachment);
  } catch (err) {
    console.error('[Portal] Upload attachment error:', err);
    res.status(500).json({ error: err.message || 'Failed to upload attachment' });
  }
});

router.get('/support/tickets/:id/attachments/:attachmentId', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { attachmentId } = req.params;
    const attachment = await portalService.getTicketAttachment(attachmentId, customer_id);
    if (!attachment) {
      return res.status(404).json({ error: 'Attachment not found' });
    }
    const filePath = path.join(TICKET_ATTACHMENTS_DIR, attachment.filename);
    res.setHeader('Content-Type', attachment.mime_type);
    res.setHeader('Content-Disposition', `attachment; filename="${attachment.original_name}"`);
    fs.createReadStream(filePath).pipe(res);
  } catch (err) {
    console.error('[Portal] Download attachment error:', err);
    res.status(500).json({ error: 'Failed to download attachment' });
  }
});

router.delete('/support/tickets/:id/attachments/:attachmentId', async (req, res) => {
  try {
    const { id, customer_id } = req.portalUser;
    const result = await portalService.deleteTicketAttachment(req.params.attachmentId, id, customer_id);
    res.json(result);
  } catch (err) {
    console.error('[Portal] Delete attachment error:', err);
    res.status(500).json({ error: 'Failed to delete attachment' });
  }
});

// ─── Support Articles (FAQ) ─────────────────────────────────────────────────────
// Returns a list of help articles for the customer portal FAQ section.
router.get('/support/articles', async (req, res) => {
  try {
    const articles = await portalService.getSupportArticles();
    res.json(articles);
  } catch (err) {
    console.error('[Portal] Support articles error:', err);
    res.status(500).json({ error: 'Failed to load articles' });
  }
});

router.get('/support/articles/:slug', async (req, res) => {
  try {
    const article = await portalService.getSupportArticle(req.params.slug);
    if (!article) {
      return res.status(404).json({ error: 'Article not found' });
    }
    res.json(article);
  } catch (err) {
    console.error('[Portal] Support article error:', err);
    res.status(500).json({ error: 'Failed to load article' });
  }
});

// ─── Company Contact Info for Portal Support ──────────────────────────────────
router.get('/support/company-info', async (req, res) => {
  try {
    const info = await portalService.getCompanyContactInfo();
    res.json(info);
  } catch (err) {
    console.error('[Portal] Company contact info error:', err);
    res.status(500).json({ error: 'Failed to load company contact info' });
  }
});

// ─── Shipments / Tracking (customer-facing, read-only) ─────────────────────────
// Today's in-flight deliveries (feeds the "Pending delivery today" banner).
// Lightweight enough for the portal to poll while the dashboard stays cached.
router.get('/deliveries/today', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const rows = await portalService.getTodayPendingDeliveries(customer_id);
    res.json(rows);
  } catch (err) {
    console.error('[Portal] Today deliveries error:', err);
    res.status(500).json({ error: 'Failed to load today deliveries' });
  }
});

// Customer-facing delivery status banners (sliding carousel like the ads).
// Every delivery status change updates the banner message for that customer.
router.get('/deliveries/banner', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const rows = await portalService.getDeliveryBanners(customer_id);
    res.json(rows);
  } catch (err) {
    console.error('[Portal] Delivery banner error:', err);
    res.status(500).json({ error: 'Failed to load delivery banners' });
  }
});

// Downloadable delivery note for a (usually delivered) delivery, strictly
// scoped to the requesting customer.
router.get('/deliveries/:id/note', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const note = await portalService.getDeliveryNoteForDelivery(req.params.id, customer_id);
    if (!note) return res.status(404).json({ error: 'Delivery note not found' });
    res.json(note);
  } catch (err) {
    console.error('[Portal] Delivery note error:', err);
    res.status(500).json({ error: 'Failed to load delivery note' });
  }
});

router.get('/shipments', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { status, search } = req.query;
    const rows = await portalService.getShipments(customer_id, {
      status: status || undefined,
      search: search || undefined,
    });
    res.json(rows);
  } catch (err) {
    console.error('[Portal] Shipments list error:', err);
    res.status(500).json({ error: 'Failed to load shipments' });
  }
});

router.get('/shipments/:id', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const row = await portalService.getShipmentById(req.params.id, customer_id );
    if (!row) return res.status(404).json({ error: 'Shipment not found' });
    res.json(row);
  } catch (err) {
    console.error('[Portal] Shipment detail error:', err);
    res.status(500).json({ error: 'Failed to load shipment' });
  }
});

// ─── Payment Processing ───────────────────────────────────────
// Create a Stripe PaymentIntent for an invoice (falls back to mock mode if Stripe not configured)
router.post('/payments/intent', async (req, res) => {
  try {
    const { customer_id } = req.portalUser;
    const { invoiceId, amount, currency = 'USD' } = req.body;
    if (!invoiceId || !amount) {
      return res.status(400).json({ error: 'invoiceId and amount are required' });
    }

    // Verify the invoice belongs to this customer
    const invoice = await portalService.getInvoiceById(invoiceId, customer_id );
    if (!invoice) return res.status(404).json({ error: 'Invoice not found' });

    if (stripe) {
      const intent = await stripe.paymentIntents.create({
        amount: Math.round(Number(amount) * 100), // cents
        currency: String(currency).toLowerCase(),
        metadata: { invoiceId: String(invoiceId), customerId: String(customer_id), portalUser: String(req.portalUser.id) },
      });
      return res.json({ clientSecret: intent.client_secret, mode: 'stripe' });
    }

    // Mock mode — returns a fake client secret for development/testing
    const mockSecret = `pi_mock_${crypto.randomBytes(16).toString('hex')}_secret`;
    res.json({ clientSecret: mockSecret, mode: 'mock' });
  } catch (err) {
    console.error('[Portal] Payment intent error:', err);
    res.status(500).json({ error: 'Failed to create payment intent' });
  }
});

// Record a completed payment — DISABLED.
// This endpoint was a SECOND, competing payment pipeline: it wrote bare
// customer_payments rows and mutated invoices directly in the cloud,
// bypassing the ERP transaction pipeline (no allocations snapshot, no
// customer.balance/ledger update, lowercase statuses). Payments must follow
// the approved workflow: customer submits a PAYMENT REQUEST → ERP verifies →
// a real customer_payment is posted through the ERP accounting pipeline →
// only then does the ledger change. Historical records are untouched.
router.post('/payments', async (req, res) => {
  res.status(403).json({ error: 'Direct portal payments are not available. Please submit a payment request; our team will confirm it once your payment is verified.' });
});

module.exports = router;
