/**
 * Portal Watermark Verification — REAL PDF output proof
 *
 * Renders ACTUAL PDFs through the production pipeline
 * (officialDocumentService → primeRenderer.cjs → @react-pdf/renderer),
 * then inspects the generated bytes with pdf.js (the repository's existing
 * PDF inspection tooling) to prove:
 *
 *   1. ERP channel PDFs  → clean, NO PORTAL COPY
 *   2. Portal channel PDFs → contain PORTAL COPY on EVERY page
 *   3. Multi-page statement (3+ pages) → watermark on every page,
 *      occurrence count >= page count
 *   4. Content parity → removing the watermark from the portal PDF leaves
 *      EXACTLY the same authoritative content as the ERP PDF (company name,
 *      phone, email, document numbers, customer, line items, amounts,
 *      balances)
 *   5. All official document types: INVOICE, QUOTATION, ORDER, RECEIPT,
 *      DELIVERY_NOTE, ACCOUNT_STATEMENT, plus all three invoice template
 *      engines (Classic fallback, Clean, Professional, Modern)
 *
 * Generated PDFs are written to backend/tests/output/portal-watermark/ for
 * visual inspection in a real PDF viewer.
 */

process.env.JWT_SECRET = 'verify-portal-watermark-jwt-secret';

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const Module = require('module');

// ── In-memory settings store (no Supabase needed) ─────────────────────────
let settingsStore = new Map();
function resetSettings(companyOverrides = {}) {
  settingsStore.set('companyConfig', {
    id: 'companyConfig',
    key: 'companyConfig',
    value: {
      companyName: 'Prime Printing Service',
      phone: '+265 992 528 222',
      email: 'info.primemw@gmail.com',
      addressLine1: 'Along M5 Road Mtakataka',
      city: 'Dedza',
      country: 'Malawi',
      currencySymbol: 'K',
      ...companyOverrides,
    },
  });
}
resetSettings();

const originalLoad = Module._load;
Module._load = function patched(request, parent, ...rest) {
  if (request === './supabaseRepository.cjs' || request.endsWith('supabaseRepository.cjs')) {
    return {
      getAll: async (table) => (table === 'settings' ? Array.from(settingsStore.values()) : []),
      getAllStrict: async (table) => (table === 'settings' ? Array.from(settingsStore.values()) : []),
      getById: async () => null,
    };
  }
  return originalLoad.call(this, request, parent, ...rest);
};

const pdfjsModulePath = path.join(__dirname, '..', '..', 'frontend', 'node_modules', 'pdfjs-dist', 'legacy', 'build', 'pdf.mjs');

async function extractPerPageText(buffer) {
  const pdfjsLib = await import(pathToFileURL(pdfjsModulePath).href);
  const loadingTask = pdfjsLib.getDocument({ data: new Uint8Array(buffer) });
  const pdf = await loadingTask.promise;
  const pages = [];
  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    const page = await pdf.getPage(pageNum);
    const textContent = await page.getTextContent();
    const pageText = textContent.items
      .map((item) => (typeof item?.str === 'string' ? item.str : ''))
      .filter(Boolean)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();
    pages.push(pageText);
  }
  await pdf.destroy();
  return pages;
}

function normalizeForParity(text) {
  return String(text || '')
    .replace(/Generated on:\s*[^\n]*/gi, 'Generated on: <normalized>')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * The watermark is drawn with letter-spacing, so pdf.js may extract it as
 * "P O R TA L C O P Y". Compare whitespace-collapsed so the match is robust.
 */
function collapsed(text) {
  return String(text || '').replace(/\s+/g, '');
}

function hasWatermark(text) {
  return collapsed(text).includes('PORTALCOPY');
}

function stripWatermark(text) {
  return String(text || '').replace(/P\s*O\s*R\s*T\s*A\s*L\s*C\s*O\s*P\s*Y/gi, '');
}

// ── Fixtures ───────────────────────────────────────────────────────────────
function invoiceFixture(prefix) {
  return {
    invoiceNumber: `${prefix}-INV-1001`, date: '2026-08-29', dueDate: '2026-09-28',
    customerName: 'Test Customer', status: 'posted',
    items: [
      { description: 'A4 Printing 1000 sheets', quantity: 2, price: 15000, total: 30000 },
      { description: 'Lamination A3', quantity: 5, price: 2000, total: 10000 },
    ],
    subtotal: 40000, tax: 0, totalAmount: 40000, amountPaid: 10000,
    notes: 'Thank you for your business.',
  };
}

function quotationFixture(prefix) {
  return {
    quotationNumber: `${prefix}-QT-2001`, date: '2026-08-29', validUntil: '2026-09-28',
    customerName: 'Test Customer', status: 'draft',
    items: [{ description: 'Branding Package', quantity: 1, price: 250000, total: 250000 }],
    subtotal: 250000, totalAmount: 250000,
  };
}

function orderFixture(prefix) {
  return {
    orderNumber: `${prefix}-ORD-3001`, date: '2026-08-29',
    customerName: 'Test Customer', status: 'confirmed',
    items: [{ description: 'Corporate Stationery', quantity: 10, price: 5000, total: 50000 }],
    subtotal: 50000, totalAmount: 50000,
  };
}

function receiptFixture(prefix) {
  return {
    receiptNumber: `${prefix}-REC-4001`, date: '2026-08-29',
    customerName: 'Test Customer',
    amountReceived: 50000, paymentMethod: 'Bank Transfer',
    appliedInvoices: [`${prefix}-INV-1001`],
    items: [{ description: 'Payment', quantity: 1, price: 50000, total: 50000 }],
    subtotal: 50000, totalAmount: 50000,
  };
}

function deliveryNoteFixture(prefix) {
  return {
    dnNumber: `${prefix}-DEL-5001`, date: '2026-08-29',
    customerName: 'Test Customer',
    items: [{ description: 'Delivered Reams', quantity: 20, price: 2500, total: 50000 }],
    subtotal: 50000, totalAmount: 50000,
  };
}

/** Statement with enough transactions to span 3+ A4 pages. */
function statementFixture(prefix, transactionCount = 60) {
  const transactions = [];
  let runningBalance = 0;
  for (let i = 0; i < transactionCount; i++) {
    const debit = (i % 3 === 0) ? 5000 + i * 100 : 0;
    const credit = (i % 3 === 1) ? 2000 + i * 50 : 0;
    runningBalance = runningBalance + debit - credit;
    transactions.push({
      date: `2026-${String((i % 12) + 1).padStart(2, '0')}-${String((i % 28) + 1).padStart(2, '0')}`,
      reference: `${prefix}-REF-${String(i + 1).padStart(4, '0')}`,
      memo: `Transaction ${i + 1} printing services`,
      debit, credit, runningBalance,
    });
  }
  return {
    statementNumber: `${prefix}-STMT-2026-0001`,
    date: '2026-08-29',
    startDate: '2026-01-01',
    endDate: '2026-08-29',
    customerName: 'Test Customer',
    currency: 'K',
    openingBalance: 0,
    transactions,
    totalInvoiced: 100000,
    totalReceived: 40000,
    finalBalance: 60000,
  };
}

// ── Runner ─────────────────────────────────────────────────────────────────
(async () => {
  let passCount = 0;
  let failCount = 0;
  const pass = (msg) => { console.log(`  ✓ PASS: ${msg}`); passCount++; };
  const fail = (msg) => { console.error(`  ✕ FAIL: ${msg}`); failCount++; };

  const outDir = path.join(__dirname, 'output', 'portal-watermark');
  fs.mkdirSync(outDir, { recursive: true });

  try {
    const officialDocumentService = require('../services/officialDocumentService.cjs');

    const typeFixtures = [
      { type: 'INVOICE', label: 'Invoice', fixture: invoiceFixture },
      { type: 'QUOTATION', label: 'Quotation', fixture: quotationFixture },
      { type: 'ORDER', label: 'Order', fixture: orderFixture },
      { type: 'RECEIPT', label: 'Receipt', fixture: receiptFixture },
      { type: 'DELIVERY_NOTE', label: 'Delivery Note', fixture: deliveryNoteFixture },
      { type: 'ACCOUNT_STATEMENT', label: 'Account Statement (multi-page)', fixture: statementFixture },
    ];

    for (const { type, label, fixture } of typeFixtures) {
      const raw = fixture('T');
      const [erp, portal] = await Promise.all([
        officialDocumentService.renderOfficialPdf({ type, rawData: raw, channel: 'erp' }),
        officialDocumentService.renderOfficialPdf({ type, rawData: raw, channel: 'portal' }),
      ]);

      const erpPages = await extractPerPageText(erp.buffer);
      const portalPages = await extractPerPageText(portal.buffer);

      fs.writeFileSync(path.join(outDir, `erp-${type}.pdf`), erp.buffer);
      fs.writeFileSync(path.join(outDir, `portal-${type}.pdf`), portal.buffer);

      // ERP: clean, no watermark
      const erpAll = erpPages.join(' ');
      if (erpPages.length >= 1 && hasWatermark(erpAll)) {
        fail(`${label} ERP PDF must NOT contain PORTAL COPY`);
      } else {
        pass(`${label} ERP PDF is clean (no PORTAL COPY)`);
      }

      // Portal: watermark on EVERY page
      let portalOk = portalPages.length >= 1;
      for (let i = 0; i < portalPages.length; i++) {
        if (!hasWatermark(portalPages[i])) {
          portalOk = false;
          fail(`${label} Portal PDF page ${i + 1} is missing PORTAL COPY`);
        }
      }
      if (portalOk) pass(`${label} Portal PDF has PORTAL COPY on every page (${portalPages.length} page(s))`);

      // Occurrence count >= page count
      const portalAll = collapsed(portalPages.join(' '));
      const occurrences = (portalAll.match(/PORTALCOPY/g) || []).length;
      if (occurrences >= portalPages.length) {
        pass(`${label} Portal PDF occurrence count (${occurrences}) >= page count (${portalPages.length})`);
      } else {
        fail(`${label} Portal PDF occurrence count (${occurrences}) < page count (${portalPages.length})`);
      }

      // Multi-page requirement for statements
      if (type === 'ACCOUNT_STATEMENT' && portalPages.length < 3) {
        fail(`${label} expected 3+ pages for multi-page watermark proof, got ${portalPages.length}`);
      } else if (type === 'ACCOUNT_STATEMENT') {
        pass(`${label} spanned ${portalPages.length} pages (multi-page watermark proven)`);
      }

      // Content parity: portal minus watermark === erp
      if (erpPages.length !== portalPages.length) {
        fail(`${label} page count mismatch (ERP ${erpPages.length} vs Portal ${portalPages.length})`);
      } else {
        let parity = true;
        for (let i = 0; i < erpPages.length; i++) {
          const erpTxt = collapsed(normalizeForParity(erpPages[i]));
          const portalTxt = collapsed(normalizeForParity(stripWatermark(portalPages[i])));
          if (erpTxt !== portalTxt) {
            parity = false;
            fail(`${label} page ${i + 1} content differs beyond the watermark.\n  ERP:    ${erpTxt.slice(0, 180)}\n  Portal: ${portalTxt.slice(0, 180)}`);
          }
        }
        if (parity) pass(`${label} portal content is identical to ERP content after removing the watermark`);
      }
    }

    // ── Invoice template engines: Clean / Professional / Modern ──────────
    const engines = [
      { engine: 'Clean', prefix: 'CLN' },
      { engine: 'Professional', prefix: 'PRF' },
      { engine: 'Modern', prefix: 'MDN' },
    ];
    for (const { engine, prefix } of engines) {
      resetSettings({ invoiceTemplates: { engine } });
      const raw = invoiceFixture(prefix);
      const [erp, portal] = await Promise.all([
        officialDocumentService.renderOfficialPdf({ type: 'INVOICE', rawData: raw, channel: 'erp' }),
        officialDocumentService.renderOfficialPdf({ type: 'INVOICE', rawData: raw, channel: 'portal' }),
      ]);
      const erpPages = await extractPerPageText(erp.buffer);
      const portalPages = await extractPerPageText(portal.buffer);
      fs.writeFileSync(path.join(outDir, `erp-INVOICE-${engine}.pdf`), erp.buffer);
      fs.writeFileSync(path.join(outDir, `portal-INVOICE-${engine}.pdf`), portal.buffer);

      const erpOk = !hasWatermark(erpPages.join(' '));
      const portalOk = portalPages.length >= 1 && portalPages.every((p) => hasWatermark(p));
      if (erpOk) pass(`${engine} engine ERP invoice is clean`);
      else fail(`${engine} engine ERP invoice unexpectedly has PORTAL COPY`);
      if (portalOk) pass(`${engine} engine Portal invoice has PORTAL COPY on every page`);
      else fail(`${engine} engine Portal invoice is missing PORTAL COPY on some page`);
    }

    // ── Authoritative identity is present in BOTH copies ──────────────────
    resetSettings();
    const identity = ['Prime Printing Service', '+265 992 528 222', 'info.primemw@gmail.com'];
    const stmt = statementFixture('T', 5);
    const { buffer: portalStmtBuffer } = await officialDocumentService.renderOfficialPdf({
      type: 'ACCOUNT_STATEMENT', rawData: stmt, channel: 'portal',
    });
    const portalStmtText = (await extractPerPageText(portalStmtBuffer)).join(' ');
    for (const value of identity) {
      if (portalStmtText.includes(value)) pass(`Portal statement carries authoritative identity: ${value}`);
      else fail(`Portal statement missing authoritative identity: ${value}`);
    }

    console.log(`\n=== PORTAL WATERMARK VERIFICATION SUMMARY ===`);
    console.log(`  Passed: ${passCount}`);
    console.log(`  Failed: ${failCount}`);
    console.log(`  PDFs written to: ${outDir}`);
    process.exit(failCount > 0 ? 1 : 0);
  } catch (err) {
    console.error('Verification failed unexpectedly:', err.stack || err.message);
    process.exit(1);
  }
})();