/**
 * portalVerificationOrigin.test.ts — ERP-side public verification URL migration proof.
 *
 * New public verification URLs generated by the ERP must point at the Prime
 * Printing Portal (VITE_PUBLIC_PORTAL_URL), never at the ERP origin.
 * Production builds fail closed when the Portal URL is unconfigured.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  SUPPORTED_DOCUMENT_TYPES,
  buildDocumentVerificationUrl,
  documentTypeSlug,
  resolveVerificationBaseUrl,
} from '../../utils/documentVerification';
import { buildSecurityQrPayload } from '../../utils/documentSecurity';

const PORTAL = 'http://localhost:3001';
const ERP_ORIGIN = 'https://127.0.0.1:5173';
const TOKEN = '9'.repeat(64);

// Cases needing a CONTROLLED import.meta.env cannot use vi.stubEnv: Vitest
// inlines `import.meta.env` at transform time (which is exactly the browser
// behavior under test), so stubs never reach an already-transformed module.
// Instead the real source is compiled with esbuild — mapping `import.meta.env`
// to a per-process global, the same technique as the server renderer bundle —
// and executed in fresh node processes with the case's environment.
const here = path.dirname(fileURLToPath(import.meta.url));
let probeCjs = '';
beforeAll(() => {
  // The probe bundle is built in a child node process: esbuild's JS API hits
  // a realm invariant (TextEncoder instanceof Uint8Array) under the jsdom
  // test environment, so it must not run in-process here.
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'portal-probe-'));
  const entry = path.join(dir, 'entry.ts');
  fs.writeFileSync(entry, [
    `import { buildDocumentVerificationUrl, resolveVerificationBaseUrl } from ${JSON.stringify(path.join(here, '..', '..', 'utils', 'documentVerification.ts'))};`,
    `const out = { base: resolveVerificationBaseUrl(), url: buildDocumentVerificationUrl({ documentType: 'invoice', documentNumber: 'INV-P726/029', verificationToken: ${JSON.stringify(TOKEN)} }) };`,
    `console.log('PROBE_RESULT:' + JSON.stringify(out));`,
  ].join('\n'));
  const builder = path.join(dir, 'build-probe.cjs');
  const esbuildMain = path.join(here, '..', '..', '..', 'node_modules', 'esbuild', 'lib', 'main.js');
  fs.writeFileSync(builder, [
    `const { buildSync } = require(${JSON.stringify(esbuildMain)});`,
    `const [,, entryFile, outFile] = process.argv;`,
    `const res = buildSync({ entryPoints: [entryFile], bundle: true, platform: 'node', format: 'cjs', write: false, define: { 'import.meta.env': '__PROBE_ENV__' } });`,
    `require('fs').writeFileSync(outFile, res.outputFiles[0].text);`,
  ].join('\n'));
  probeCjs = path.join(dir, 'probe.cjs');
  execFileSync(process.execPath, [builder, entry, probeCjs], { encoding: 'utf8', timeout: 120000 });
}, 180000);

function probeCase(opts: { env?: Record<string, unknown>; nodeEnv?: string; windowOrigin?: string }): { base: string; url: string | null } {
  const setup = `globalThis.__PROBE_ENV__=${JSON.stringify({ DEV: false, PROD: false, MODE: 'test', ...(opts.env || {}) })};`
    + (opts.windowOrigin ? `globalThis.window={location:{origin:${JSON.stringify(opts.windowOrigin)}}};` : '');
  const out = execFileSync(process.execPath, ['-e', `${setup}require(${JSON.stringify(probeCjs)});`], {
    env: { ...process.env, NODE_ENV: opts.nodeEnv || 'test' },
    encoding: 'utf8',
    timeout: 60000,
  });
  return JSON.parse(out.trim().split('\n').pop()!.replace('PROBE_RESULT:', '')) as { base: string; url: string | null };
}

describe('development Portal origin (runner env = configured dev env)', () => {
  it('builds the exact Portal URL for INV-P726/029 (never the ERP origin)', () => {
    // The Vitest run loads frontend/.env, so the statically injected env
    // carries the configured dev Portal origin here.
    expect(resolveVerificationBaseUrl()).toBe(PORTAL);
    const url = buildDocumentVerificationUrl({
      documentType: 'invoice',
      documentNumber: 'INV-P726/029',
      verificationToken: TOKEN,
    });
    expect(url).toBe(`${PORTAL}/#/verify/invoice/INV-P726%2F029?t=${TOKEN}`);
    expect(url).not.toContain(ERP_ORIGIN);
    expect(url).not.toContain('127.0.0.1:5173');
  });

  it('normalizes a Portal URL with a trailing slash (no double slash)', () => {
    const url = buildDocumentVerificationUrl({
      documentType: 'invoice',
      documentNumber: 'INV-P726/029',
      verificationToken: TOKEN,
    }, `${PORTAL}/`);
    expect(url).toBe(`${PORTAL}/#/verify/invoice/INV-P726%2F029?t=${TOKEN}`);
    expect(url).not.toContain(`${PORTAL}//#/verify/`);
  });

  it('encodes the slash in the document number exactly once', () => {
    const url = buildDocumentVerificationUrl({
      documentType: 'invoice',
      documentNumber: 'INV-P726/029',
      verificationToken: TOKEN,
    })!;
    expect(url).toContain('INV-P726%2F029');
    expect(url).not.toContain('INV-P726/029');
    expect(url).not.toContain('%252F');
  });

  it('production placeholder origin is used verbatim (no ERP fallback)', () => {
    // Controlled env matrix runs against the real compiled source (see
    // probeCase): static injection makes vi.stubEnv ineffective in-runner.
    const r = probeCase({ env: { VITE_PUBLIC_PORTAL_URL: 'https://portal.example.test', PROD: true, MODE: 'production' }, nodeEnv: 'production' });
    expect(r.base).toBe('https://portal.example.test');
    expect(r.url).toBe(`https://portal.example.test/#/verify/invoice/INV-P726%2F029?t=${TOKEN}`);
    expect(r.url).not.toContain(ERP_ORIGIN);
  });

  it('leaves the verification token byte-identical', () => {
    const url = buildDocumentVerificationUrl({
      documentType: 'invoice',
      documentNumber: 'INV-P726/029',
      verificationToken: TOKEN,
    })!;
    expect(url.split('?t=')[1]).toBe(TOKEN);
  });
});

describe('all supported document types use the Portal origin', () => {
  const numbers: Record<string, any> = {
    invoice: { invoiceNumber: 'INV-P726/029' },
    receipt: { receiptNumber: 'PAY-P726/001' },
    quotation: { quotationNumber: 'QTN-P726/001' },
    sales_order: { orderNumber: 'SO-P726/001' },
    purchase_order: { order_number: 'PO-P726/001' },
    delivery_note: { dnNumber: 'DN-P726/001' },
    supplier_payment: { documentType: 'supplier_payment', paymentId: 'SPAY-P726/001', supplierName: 'Paper Supplier' },
    statement: { documentType: 'statement', statementNumber: 'STMT-P726-001' },
  };

  it('covers every supported type (no ERP-origin stragglers)', () => {
    expect(SUPPORTED_DOCUMENT_TYPES.length).toBeGreaterThan(0);
    for (const type of SUPPORTED_DOCUMENT_TYPES) {
      const slug = documentTypeSlug(type);
      const url = buildDocumentVerificationUrl({
        documentType: type,
        documentNumber: 'DOC-P726/001',
        verificationToken: TOKEN,
      })!;
      expect(url.startsWith(`${PORTAL}/#/verify/${slug}/`)).toBe(true);
      expect(url).toContain(`?t=${TOKEN}`);
      expect(url).not.toContain(ERP_ORIGIN);
    }
  });

  it('QR payloads route through the canonical Portal builder', () => {
    for (const type of SUPPORTED_DOCUMENT_TYPES) {
      const payload = buildSecurityQrPayload(
        { ...numbers[type], date: '2026-09-01', verificationToken: TOKEN },
        'Prime Printing Service'
      );
      const slug = documentTypeSlug(type);
      expect(payload.startsWith(`${PORTAL}/#/verify/${slug}/`)).toBe(true);
      expect(payload).toContain(`?t=${TOKEN}`);
      expect(payload).not.toContain(ERP_ORIGIN);
    }
  });
});

describe('missing Portal configuration (controlled compiled matrix)', () => {
  it('production fails closed — never generates an ERP-origin public URL', () => {
    const r = probeCase({ env: { PROD: true, MODE: 'production' }, nodeEnv: 'production' });
    expect(r.base).toBe('');
    expect(r.url).toBeNull();
  });

  it('explicit base URLs still work when the env is missing in production', () => {
    const url = buildDocumentVerificationUrl(
      { documentType: 'invoice', documentNumber: 'INV-P726/029', verificationToken: TOKEN },
      PORTAL
    );
    expect(url).toBe(`${PORTAL}/#/verify/invoice/INV-P726%2F029?t=${TOKEN}`);
  });

  it('dev without Portal env falls back to the running-app origin (dev only)', () => {
    // This is the exact mechanism that produced the observed INV-P726/021
    // ERP-origin URL: with no injected Portal origin, a dev browser resolves
    // window.location.origin (here stubbed to the dev-server origin).
    const r = probeCase({ env: {}, nodeEnv: 'test', windowOrigin: ERP_ORIGIN });
    expect(r.base).toBe(ERP_ORIGIN);
    expect(r.url).toBe(`${ERP_ORIGIN}/#/verify/invoice/INV-P726%2F029?t=${TOKEN}`);
  });

  it('dev without Portal env and without window stays empty', () => {
    const r = probeCase({ env: {}, nodeEnv: 'test' });
    expect(r.base).toBe('');
    expect(r.url).toBeNull();
  });
});

describe('Vite env-injection compatibility (regression guard for INV-P726/021)', () => {
  it('reads import.meta.env through a statically analyzable member chain', () => {
    // Root cause of the INV-P726/021 ERP-origin URL: `(import.meta as any)?.env`
    // defeats Vite's static import.meta.env substitution (dev serve AND build),
    // so real browsers always read the native empty import.meta and fall back
    // to window.location.origin. The access MUST stay `import.meta.env...`.
    const here = path.dirname(fileURLToPath(import.meta.url));
    const raw = fs.readFileSync(path.join(here, '..', '..', 'utils', 'documentVerification.ts'), 'utf8');
    // Strip comments: the explanatory notes below the fix name the old shape.
    const src = raw.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|\s)\/\/.*$/gm, '$1');
    expect(src).not.toMatch(/import\.meta\?\.env/);
    expect(src).not.toMatch(/\(import\.meta as any\)\?\.env/);
    expect(src).toMatch(/import\.meta(\s+as\s+any\))?\.env/);
  });
});
